server:
  port : 6060

spring:
  application:
    name: order-service

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order-service-db
    username: order-service-user
    password: order-service-password
  jpa:
    show-sql: true

  flyway:
    locations: classpath:db/migration

management:
  endpoints:
    web:
      base-path: "/api/management"
      exposure:
        include: "health,info"